---
title: ""
author: ""
date: ""
output: html_document
  mathjax: "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
---

En el contexto de *Asset Pricing* y en particular en **Option Valuation** es de interés simular posibles trayectorias para un determinado activo, para esto es necesario establecer una froma funcional para el precio.

Una de las herramientas más utilizadas para esta tarea es el *Movimiento Browniano Geométrico*. Hay que notar que este **no es un modelo de series de tiempo** es una **ecuasión diferencial estocástica**. 

Partiendo de que los log-returns se distribuyen razonablemente normales la forma funcional de una trayectoria del precio es la siguiente: $S_t = S_0 e^{\{(\mu-\frac{1}{2}\sigma^2)dt+\sigma W_t \}}$, donde:

  + $\mu$ es el drift del proceso
  + $\sigma$ es la volatilidad del proceso
  + $dt$ es el salto
  + $W_t$ son la inovaciones del proceso
    
Nuestra Intención es generar un dashboard en el cual el usario pueda ajustar este modelo para diferentes horizontes para varios activos del mercado mexicano.

